version: '3.3'

services:
  db:
    image: postgres
    container_name: db
    volumes:
     - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: PowerProbe
      POSTGRES_PASSWORD: Powerprobe@123
      POSTGRES_DB: PowerProbeDb
    ports:
      - '5432:5432'
    networks:
      pp-network:
        ipv4_address: 172.28.0.2

  app:
    container_name: app
    build:
      context: .
      args:
        - DEV=true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./apps:/apps
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST = db
      - DB_NAME = PowerProbeDb
      - DB_USER = PowerProbe
      - DB_PASSWORD = Powerprobe@123

    networks:
      pp-network:
       ipv4_address: 172.28.0.3

networks:
  pp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  db-data: